services:
  musica-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MONGO_URI=mongodb://mongodb:27017/musica_prod
    depends_on:
      - mongodb
    networks:
      - musica-net

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - musica-net
    volumes:
      - mongo-data:/data/db

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8082:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - musica-net
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
    restart: always

networks:
  musica-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  jenkins_home:
    driver: local
